repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-duckdb"]
      - id: sqlfluff-fix
        additional_dependencies: ["dbt-duckdb"]

ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
