imdb_movies:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: database/imdb_movies.duckdb
      threads: 4

    prod:
      type: duckdb
      path: database/prod.duckdb
      threads: 4
